// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Indicates whether this file is a placeholder (no real options).
  /// The FlutterFire CLI generates real values and sets this to `false`.
  static const bool isPlaceholder = false;
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUvZYk-wGzxzIItuSp7RbhAdMIwDaAmkk',
    appId: '1:1021325520322:web:1a3d42881904ff71513a5b',
    messagingSenderId: '1021325520322',
    projectId: 'blood-donation-33eec',
    authDomain: 'blood-donation-33eec.firebaseapp.com',
    storageBucket: 'blood-donation-33eec.firebasestorage.app',
    measurementId: 'G-0JHZJRQT64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPJp13xzX18yrJIqFVCTC0xlxVOo31QPo',
    appId: '1:1021325520322:android:33c9daa3498ed333513a5b',
    messagingSenderId: '1021325520322',
    projectId: 'blood-donation-33eec',
    storageBucket: 'blood-donation-33eec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcF5mxZ-OrCyiA87SDRnDvcUdN4oCHWqM',
    appId: '1:1021325520322:ios:7e823d15c99f8acf513a5b',
    messagingSenderId: '1021325520322',
    projectId: 'blood-donation-33eec',
    storageBucket: 'blood-donation-33eec.firebasestorage.app',
    iosClientId:
        '1021325520322-a0p6o1h1lp2tcv9ejtfgrernq410hag1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBank1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUvZYk-wGzxzIItuSp7RbhAdMIwDaAmkk',
    appId: '1:1021325520322:web:1a3d42881904ff71513a5b',
    messagingSenderId: '1021325520322',
    projectId: 'blood-donation-33eec',
    authDomain: 'blood-donation-33eec.firebaseapp.com',
    storageBucket: 'blood-donation-33eec.firebasestorage.app',
    measurementId: 'G-0JHZJRQT64',
  );
}
