/// Bangladesh Division, District, and Upazila data for location selection
class BangladeshLocations {
  // List of Divisions in Bangladesh
  static const List<String> divisions = [
    'Dhaka',
    'Chittagong',
    'Rajshahi',
    'Khulna',
    'Barisal',
    'Sylhet',
    'Rangpur',
    'Mymensingh',
  ];

  // Districts by Division
  static const Map<String, List<String>> districtsByDivision = {
    'Dhaka': [
      'Dhaka',
      'Faridpur',
      'Gazipur',
      'Gopalganj',
      'Kishoreganj',
      'Madaripur',
      'Manikganj',
      'Munshiganj',
      'Narayanganj',
      'Narsingdi',
      'Rajbari',
      'Shariatpur',
      'Tangail',
    ],
    'Chittagong': [
      'Chittagong',
      'Bandarban',
      'Brahmanbaria',
      'Chandpur',
      'Comilla',
      'Cox\'s Bazar',
      'Feni',
      'Khagrachari',
      'Lakshmipur',
      'Noakhali',
      'Rangamati',
    ],
    'Rajshahi': [
      'Rajshahi',
      'Bogra',
      'Joypurhat',
      'Naogaon',
      'Natore',
      'Chapainawabganj',
      'Pabna',
      'Sirajganj',
    ],
    'Khulna': [
      'Khulna',
      'Bagerhat',
      'Chuadanga',
      'Jessore',
      'Jhenaidah',
      'Kushtia',
      'Magura',
      'Meherpur',
      'Narail',
      'Satkhira',
    ],
    'Barisal': [
      'Barisal',
      'Barguna',
      'Bhola',
      'Jhalokati',
      'Patuakhali',
      'Pirojpur',
    ],
    'Sylhet': ['Sylhet', 'Habiganj', 'Moulvibazar', 'Sunamganj'],
    'Rangpur': [
      'Rangpur',
      'Dinajpur',
      'Gaibandha',
      'Kurigram',
      'Lalmonirhat',
      'Nilphamari',
      'Panchagarh',
      'Thakurgaon',
    ],
    'Mymensingh': ['Mymensingh', 'Jamalpur', 'Netrokona', 'Sherpur'],
  };

  // Upazilas by District
  static const Map<String, Map<String, List<String>>> upazilasByDistrict = {
    'Dhaka': {
      'Dhaka': [
        'Adabor',
        'Badda',
        'Bangshal',
        'Bimanbandar',
        'Cantonment',
        'Chackbazar',
        'Dakshinkhan',
        'Darus Salam',
        'Demra',
        'Dhanmondi',
        'Gendaria',
        'Gulshan',
        'Hazaribagh',
        'Jatrabari',
        'Kafrul',
        'Kalabagan',
        'Kamrangirchar',
        'Khilgaon',
        'Khilkhet',
        'Kotwali',
        'Lalbagh',
        'Mirpur',
        'Mohammadpur',
        'Motijheel',
        'New Market',
        'Pallabi',
        'Paltan',
        'Ramna',
        'Rampura',
        'Sabujbagh',
        'Shah Ali',
        'Shahbagh',
        'Sher-e-Bangla Nagar',
        'Shyampur',
        'Sutrapur',
        'Tejgaon',
        'Tejgaon Industrial Area',
        'Turag',
        'Uttara',
        'Uttarkhan',
        'Vatara',
        'Wari',
      ],
      'Gazipur': [
        'Gazipur Sadar',
        'Kaliakair',
        'Kapasia',
        'Sreepur',
        'Kaliganj',
      ],
      'Narayanganj': [
        'Narayanganj Sadar',
        'Araihazar',
        'Bandar',
        'Rupganj',
        'Sonargaon',
      ],
      'Tangail': [
        'Tangail Sadar',
        'Basail',
        'Bhuapur',
        'Delduar',
        'Dhanbari',
        'Ghatail',
        'Gopalpur',
        'Kalihati',
        'Madhupur',
        'Mirzapur',
        'Nagarpur',
        'Sakhipur',
      ],
    },
    'Chittagong': {
      'Chittagong': [
        'Anwara',
        'Banshkhali',
        'Boalkhali',
        'Chandanaish',
        'Fatikchhari',
        'Hathazari',
        'Lohagara',
        'Mirsharai',
        'Patiya',
        'Rangunia',
        'Raozan',
        'Sandwip',
        'Satkania',
        'Sitakunda',
      ],
      'Cox\'s Bazar': [
        'Cox\'s Bazar Sadar',
        'Chakaria',
        'Kutubdia',
        'Maheshkhali',
        'Pekua',
        'Ramu',
        'Teknaf',
        'Ukhia',
      ],
      'Comilla': [
        'Comilla Sadar',
        'Barura',
        'Brahmanpara',
        'Burichang',
        'Chandina',
        'Chauddagram',
        'Daudkandi',
        'Debidwar',
        'Homna',
        'Laksam',
        'Meghna',
        'Muradnagar',
        'Nangalkot',
        'Titas',
      ],
    },
    'Rajshahi': {
      'Rajshahi': [
        'Bagha',
        'Bagmara',
        'Charghat',
        'Durgapur',
        'Godagari',
        'Mohanpur',
        'Paba',
        'Puthia',
        'Tanore',
      ],
      'Bogra': [
        'Adamdighi',
        'Bogra Sadar',
        'Dhunat',
        'Dhupchanchia',
        'Gabtali',
        'Kahaloo',
        'Nandigram',
        'Sariakandi',
        'Shajahanpur',
        'Sherpur',
        'Shibganj',
        'Sonatola',
      ],
    },
    'Khulna': {
      'Khulna': [
        'Batiaghata',
        'Dacope',
        'Dumuria',
        'Dighalia',
        'Koyra',
        'Paikgachha',
        'Phultala',
        'Rupsa',
        'Terokhada',
      ],
      'Jessore': [
        'Abhaynagar',
        'Bagherpara',
        'Chaugachha',
        'Jhikargachha',
        'Keshabpur',
        'Jessore Sadar',
        'Manirampur',
        'Sharsha',
      ],
    },
    'Sylhet': {
      'Sylhet': [
        'Sylhet Sadar',
        'Beanibazar',
        'Bishwanath',
        'Companiganj',
        'Fenchuganj',
        'Golapganj',
        'Gowainghat',
        'Jaintiapur',
        'Kanaighat',
        'Zakiganj',
      ],
    },
    'Barisal': {
      'Barisal': [
        'Agailjhara',
        'Babuganj',
        'Bakerganj',
        'Banaripara',
        'Barisal Sadar',
        'Gournadi',
        'Hizla',
        'Mehendiganj',
        'Muladi',
        'Wazirpur',
      ],
    },
    'Rangpur': {
      'Rangpur': [
        'Badarganj',
        'Gangachhara',
        'Kaunia',
        'Rangpur Sadar',
        'Mithapukur',
        'Pirgachha',
        'Pirganj',
        'Taraganj',
      ],
      'Dinajpur': [
        'Birampur',
        'Birganj',
        'Biral',
        'Bochaganj',
        'Chirirbandar',
        'Dinajpur Sadar',
        'Fulbari',
        'Ghoraghat',
        'Hakimpur',
        'Kaharole',
        'Khansama',
        'Nawabganj',
        'Parbatipur',
      ],
    },
    'Mymensingh': {
      'Mymensingh': [
        'Bhaluka',
        'Dhobaura',
        'Fulbaria',
        'Gaffargaon',
        'Gauripur',
        'Haluaghat',
        'Ishwarganj',
        'Mymensingh Sadar',
        'Muktagachha',
        'Nandail',
        'Phulpur',
        'Trishal',
      ],
    },
  };

  /// Get list of districts for a given division
  static List<String> getDistricts(String division) {
    return districtsByDivision[division] ?? [];
  }

  /// Get list of upazilas for a given division and district
  static List<String> getUpazilas(String division, String district) {
    return upazilasByDistrict[division]?[district] ?? [];
  }
}
